"use client";

import type { InvoiceOut, UserOut } from "@/lib/types";

const monthName = (y: number, m: number) =>
  new Date(y, m - 1, 1).toLocaleDateString("en-IN", { month: "long", year: "numeric" });

/** Opens a clean, printable monthly invoice in a new window. */
export function printInvoice(inv: InvoiceOut, user: UserOut | null) {
  const w = window.open("", "_blank", "width=680,height=800");
  if (!w) return;
  const money = (n: number) => `Rs ${Number(n).toFixed(2)}`;
  const rows = inv.lines
    .map(
      (ln) => `<tr>
        <td style="text-transform:capitalize">${ln.meal_type} — ${ln.item_name}${
          ln.kind === "adhoc" ? " <em>(order)</em>" : ""
        }</td>
        <td>${ln.plates}</td>
        <td>${money(ln.unit_price)}</td>
        <td>${money(ln.line_total)}</td>
      </tr>`,
    )
    .join("");
  w.document.write(`<!doctype html><html><head><meta charset="utf-8">
  <title>Invoice #${inv.id} — GharSe Tiffin</title>
  <style>
    body{font-family:Georgia,serif;color:#4a3428;margin:0;padding:40px;background:#fffaf3}
    h1{color:#c94d1a;margin:0 0 4px}
    .muted{color:#8a7a70;font-size:13px}
    table{width:100%;border-collapse:collapse;margin-top:24px}
    td,th{padding:10px 8px;border-bottom:1px solid #e8d8c8;text-align:left;font-size:14px}
    th{font-size:12px;text-transform:uppercase;letter-spacing:.05em;color:#8a7a70}
    .meta td:first-child{font-size:12px;text-transform:uppercase;letter-spacing:.05em;color:#8a7a70;width:120px}
    .total{font-size:18px;font-weight:bold}
    .badge{display:inline-block;padding:2px 10px;border-radius:999px;font-size:12px;font-weight:bold;text-transform:capitalize}
    .paid{background:#d1fae5;color:#065f46}
    .pending,.partial{background:#fef3c7;color:#92400e}
    .overdue{background:#fee2e2;color:#991b1b}
    .foot{margin-top:40px;font-size:12px;color:#8a7a70}
    @media print{body{padding:20px}}
  </style></head><body>
  <h1>GharSe Tiffin</h1>
  <div class="muted">Subscription tiffin · demo invoice (payments simulated)</div>
  <table class="meta">
    <tr><td>Invoice</td><td>#${inv.id}</td></tr>
    <tr><td>Billing period</td><td>${monthName(inv.period_year, inv.period_month)}</td></tr>
    <tr><td>Customer</td><td>${user?.name ?? ""} · ${user?.phone ?? ""}</td></tr>
    <tr><td>Address</td><td>${user?.address ?? "—"} ${user?.pincode ?? ""}</td></tr>
    <tr><td>Due date</td><td>${inv.due_date ?? "—"}</td></tr>
    <tr><td>Status</td><td><span class="badge ${inv.effective_status}">${inv.effective_status}</span>${
      inv.txn_id ? ` · ${inv.txn_id} (${inv.method ?? ""})` : ""
    }</td></tr>
  </table>
  <table>
    <thead><tr><th>Item</th><th>Plates</th><th>Unit</th><th>Amount</th></tr></thead>
    <tbody>${rows}</tbody>
    <tfoot>
      <tr><td colspan="3">Total (${inv.plates} plates)</td><td>${money(inv.amount)}</td></tr>
      <tr><td colspan="3">Paid</td><td>${money(inv.amount_paid)}</td></tr>
      <tr><td class="total" colspan="3">Amount due</td><td class="total">${money(inv.amount_due)}</td></tr>
    </tfoot>
  </table>
  <div class="foot">This is a demo invoice generated by GharSe Tiffin. No real payment was processed.</div>
  <script>window.onload=()=>window.print()</script>
  </body></html>`);
  w.document.close();
}
